const PRODUCTS={
polo:{name:"NachyGolf Embroidered Performance Polo",price:79.99,prices:{"2XL":81.99},image:"https://cdn.shopify.com/s/files/1/1026/1836/6323/files/web-front-white.jpg?v=1791355650",sizes:["S","M","L","XL","2XL"],desc:"Clean performance. Course-ready style. Lightweight, sweat-wicking comfort with embroidered NachyGolf detail."},
tee:{name:"NachyGolf Scenic Course T-Shirt",price:39.99,prices:{"2XL":41.99,"3XL":43.99},image:"https://cdn.shopify.com/s/files/1/1026/1836/6323/files/web-front-white-3.jpg?v=1791355644",sizes:["M","L","XL","2XL","3XL"],desc:"Golf-inspired and easy to wear anywhere. Heavyweight garment-dyed cotton with a relaxed fit."},
hoodie:{name:"NachyGolf Retro Script Golf Hoodie",price:34.88,prices:{"2XL":37.63},image:"https://cdn.shopify.com/s/files/1/1026/1836/6323/files/Folded_White.jpg?v=1791406169",gallery:["https://cdn.shopify.com/s/files/1/1026/1836/6323/files/Folded_White.jpg?v=1791406169","https://cdn.shopify.com/s/files/1/1026/1836/6323/files/Back_White-2.jpg?v=1791406174"],sizes:["S","M","L","XL","2XL"],desc:"Your go-to layer for cool days on and off the course. Medium-weight fleece with a classic fit."},
towel:{name:"NachyGolf Microfiber Golf Towel — Blue Splash",price:20.79,image:"https://cdn.shopify.com/s/files/1/1026/1836/6323/files/web-front.jpg?v=1791355656",sizes:["One Size"],desc:"Built for the bag. Quick-drying microfiber with a metal ring and grommet for easy attachment."},
balls:{name:"NachyGolf Golf Balls — 6 Pack",price:27.16,cls:"balls",mark:"● ● ●",sizes:["6 Pack"],desc:"Bring NachyGolf to every tee box. A six-pack of branded golf balls ready for your next round."}
};
const money=n=>"$"+n.toFixed(2);
const unitPrice=(p,size)=>p.prices?.[size]??p.price;
const getCart=()=>{try{return JSON.parse(localStorage.getItem("ngCart")||"[]")}catch{return[]}};
const saveCart=c=>{localStorage.setItem("ngCart",JSON.stringify(c));updateCount()};
function updateCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=n)}
function add(id,size){let c=getCart(),x=c.find(i=>i.id===id&&i.size===size);x?x.qty++:c.push({id,size,qty:1});saveCart(c);location.href="cart.html"}
function removeItem(i){let c=getCart();c.splice(i,1);saveCart(c);renderCart()}
function changeQty(i,delta){let c=getCart();if(!c[i])return;c[i].qty+=delta;if(c[i].qty<=0)c.splice(i,1);saveCart(c);renderCart()}
function renderProduct(){const el=document.querySelector("#product-page");if(!el)return;const id=new URLSearchParams(location.search).get("id");const p=PRODUCTS[id];if(!p){el.innerHTML='<div class="not-found"><h1>Product not found.</h1><a class="btn primary" href="shop.html">BACK TO SHOP</a></div>';return}document.title=p.name+" — NachyGolf";const visual=p.image?'<div class="product-gallery"><div class="product-photo"><img id="main-product-image" src="'+p.image+'" alt="'+p.name+'"></div>'+(p.gallery?.length>1?'<div class="product-thumbs">'+p.gallery.map((src,i)=>'<button class="product-thumb '+(i===0?'active':'')+'" data-src="'+src+'" aria-label="View product image '+(i+1)+'"><img src="'+src+'" alt=""></button>').join("")+'</div>':'')+'</div>':'<div class="product-visual '+p.cls+'">'+p.mark+'</div>';el.innerHTML=visual+'<div class="product-info"><p class="eyebrow">NACHYGOLF</p><h1>'+p.name+'</h1><div class="product-price" id="product-price">'+money(unitPrice(p,p.sizes[0]))+'</div><p>'+p.desc+'</p><label for="size">SIZE / OPTION</label><select id="size">'+p.sizes.map(s=>'<option>'+s+'</option>').join("")+'</select><button class="btn primary add-btn" id="add">ADD TO CART</button><p class="fine">Produced to order. All sales are final except where required by law or for eligible damaged, defective, or incorrect items.</p></div>';const size=document.querySelector("#size");size.onchange=()=>document.querySelector("#product-price").textContent=money(unitPrice(p,size.value));document.querySelector("#add").onclick=()=>add(id,size.value);document.querySelectorAll(".product-thumb").forEach(t=>t.onclick=()=>{document.querySelector("#main-product-image").src=t.dataset.src;document.querySelectorAll(".product-thumb").forEach(x=>x.classList.remove("active"));t.classList.add("active")})}
function renderCart(){const el=document.querySelector("#cart-items");if(!el)return;const c=getCart().filter(x=>PRODUCTS[x.id]);if(!c.length){el.innerHTML='<div class="empty">Your cart is empty.<br><a class="btn primary" href="shop.html">SHOP GEAR</a></div>';document.querySelector("#cart-summary").innerHTML="";return}let total=0;el.innerHTML=c.map((x,i)=>{const p=PRODUCTS[x.id],price=unitPrice(p,x.size);total+=price*x.qty;return '<div class="cart-row"><div><strong>'+p.name+'</strong><span>'+x.size+'</span></div><div class="qty"><button aria-label="Decrease quantity" onclick="changeQty('+i+',-1)">−</button><b>'+x.qty+'</b><button aria-label="Increase quantity" onclick="changeQty('+i+',1)">+</button></div><b>'+money(price*x.qty)+'</b><button class="remove" onclick="removeItem('+i+')">Remove</button></div>'}).join("");document.querySelector("#cart-summary").innerHTML='<div class="summary"><span>Subtotal</span><strong>'+money(total)+'</strong></div><button class="btn primary checkout" disabled>CHECKOUT — COMING NEXT</button><p class="fine">Secure checkout will be enabled when payment and fulfillment are connected.</p>'}
updateCount();renderProduct();renderCart();
const filterButtons=document.querySelectorAll(".filter"),collectionCards=document.querySelectorAll(".photo-card[data-cat]");filterButtons.forEach(btn=>btn.addEventListener("click",()=>{filterButtons.forEach(b=>b.classList.remove("active"));btn.classList.add("active");const cat=btn.dataset.filter;collectionCards.forEach(card=>card.hidden=!(cat==="all"||card.dataset.cat===cat));}));